version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    groups:
      all-nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-github-actions:
        patterns:
          - "*"
